# Generated by Django 4.0.6 on 2022-07-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
    ]
