# Generated by Django 4.0.6 on 2022-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_remove_city_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Город'), (1, 'ПГТ')], default=0, verbose_name='Тип'),
        ),
    ]
